Fix assumed role session refresh
The assume_role function expects the AWS_Audit_Info object as parameter, currently the AWS_Assume_Role object is sent.
Currently when the session is refreshed the following error is thrown:
`2022-12-25 17:33:35,036 [File: aws_provider.py:99]      [Module: aws_provider]   CRITICAL: AttributeError -- 'AWS_Assume_Role' object has no attribute 'original_session'`